version: '3.8'

services:
  app1:
    build:
      context: ./app1
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 3
      timeout: 2s

  app2:
    build:
      context: ./app2
    ports:
      - "3001:3001"
    networks:
      - app_network
    environment:
      - PORT=3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 10s
      retries: 3
      timeout: 2s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
